name: multisurv
channels:
  - pytorch
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - python=3.8
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - scipy
  - seaborn
  - lifelines
  - imageio
  - opencv
  - pytorch
  - torchvision
  - h5py
  - pip
  - pip:
      - pycox
      - torchtuples
      - pysurvival
      - tqdm
      - jupyter
      - tables
      - xlrd
      - openpyxl
