name: multisurv
channels:
  - pytorch
  - nvidia  # Added for CUDA support
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - python=3.8
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - scikit-image
  - scipy
  - seaborn
  - lifelines
  - imageio
  - opencv
  - pytorch-cuda=11.8  # GPU-enabled PyTorch
  - pytorch
  - torchvision
  - h5py
  - pymongo
  - tensorboard
  - pip
  - pip:
      - pycox
      - torchtuples
      - pysurvival
      - tqdm
      - jupyter
      - tables
      - xlrd
      - openpyxl